trigger: 
 - master

pool:
  vmImage: 'vs2017-win2016'  # need a Windows host because the Hugo task uses PowerShell

steps:
- task: HugoTask@1
  inputs:
    source: '\'
    destination: '\'
    extendedVersion: true
    baseURL: 'https://ricoinfo.azurewebsites.net'
    buildDrafts: true
    buildExpired: true
    buildFuture: true
    uglyURLs: true