#
# Azure pipeline to build and publish a hugo blog release
# github.com/kurtmkurtm
#

trigger:
- master

pool:
  vmImage: "ubuntu-18.04"

variables:
  blog.path: './quickstart'

steps:
- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb  
  displayName: "Download HUGO"

- script: 'sudo dpkg -i hugo_0.70.0_Linux-64bit.deb'
  displayName: "Install HUGO"

- script: |
   cd $ (blog.path)
   hugo --log -v
  displayName: 'Generate Blog'

- task: CopyFiles@2
  displayName: 'Copy Blog'
  inputs:
    SourceFolder: '$ (blog.path) / public'
    Contents: "**"
    TargetFolder: '$ (Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$ (Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'