trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

steps:
- task: HugoTask@1
  inputs:
    source: '/src/'
    destination: '/build'
    extendedVersion: true
    baseURL: 'https://ricoinfo.azurewebsites.net'
    buildDrafts: true
    buildExpired: true
    buildFuture: true
    uglyURLs: true